version: '3.9'

services:
  node:
    image: dockercommands
    build:
      context: .
      dockerfile: node.dockerfile
      args:
        PACKAGES: "nano wget curl"
    ports:
      - "3000:3000"
    volumes:
      - ./logs:/var/www/logs
    environment:
      - NODE_ENV=production
      - APP_VERSION=1.0
    depends_on: 
      - mongodb
      
  mongodb:
    image: mongo
    volumes:
      - db:/data/db

volumes:
  db:
