services:
  db:
    image: postgres:15.1-alpine
    environment:
      - POSTGRES_PASSWORD=foobarbaz
    ports:
      - "5432:5432"
  api-node:
    build: ./api-node
    ports:
      - "3000:3000"
    depends_on:
      - db
  api-golang:
    build: ./api-golang
    ports:
      - "8080:8080"
    depends_on:
      - db
  client:
    build: ./client-react
    ports:
      - "8088:8080"
    depends_on:
      - api-node
      - api-golang