version: '3.9'

services:

  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL} 
    depends_on:
      - db
  db:
    image: mysql:8.4.0
    ports:
      - "3306:3306"
    volumes:
      - dbdaten:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=tododb
  
  tool:
    image: phpmyadmin:5-apache
    ports:
      - "8085:80"
    environment:
      - PMA_ARBITRARY=1
    depends_on: 
      - db

volumes:
  dbdaten:
